--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chad/Pictures/nord/audio-bunny.png"

-- Special
background="#101a1b"
foreground="#ebb2f5"
cursor="#ebb2f5"

-- Colors
color0="#101a1b"
color1="#73458E"
color2="#7E42A1"
color3="#843DAE"
color4="#904DAE"
color5="#AE57CE"
color6="#D068EA"
color7="#ebb2f5"
color8="#a47cab"
color9="#73458E"
color10="#7E42A1"
color11="#843DAE"
color12="#904DAE"
color13="#AE57CE"
color14="#D068EA"
color15="#ebb2f5"
