# Shell variables
# Generated by 'wal'
wallpaper='/home/chad/Pictures/nord/audio-bunny.png'

# Special
background='#101a1b'
foreground='#ebb2f5'
cursor='#ebb2f5'

# Colors
color0='#101a1b'
color1='#73458E'
color2='#7E42A1'
color3='#843DAE'
color4='#904DAE'
color5='#AE57CE'
color6='#D068EA'
color7='#ebb2f5'
color8='#a47cab'
color9='#73458E'
color10='#7E42A1'
color11='#843DAE'
color12='#904DAE'
color13='#AE57CE'
color14='#D068EA'
color15='#ebb2f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
